// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyDatabase.h"
#include "Fear_Of_A_Blak_PlanetExpressoScripts.h"
#include "Fear_Of_A_Blak_PlanetDatabase.generated.h"

UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 UFear_Of_A_Blak_PlanetDatabase() 
	{
		SetExpressoScriptsClass(UFear_Of_A_Blak_PlanetExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static UFear_Of_A_Blak_PlanetDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<UFear_Of_A_Blak_PlanetDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UFear_Of_A_Blak_PlanetGlobalVariables* GetGVs() const override
	{
		return static_cast<UFear_Of_A_Blak_PlanetGlobalVariables*>(Super::GetGVs());
	}
	/** Gets the current runtime instance of a set of GVs. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	UFear_Of_A_Blak_PlanetGlobalVariables* GetRuntimeGVs(UArticyAlternativeGlobalVariables* Asset) const override
	{
		return static_cast<UFear_Of_A_Blak_PlanetGlobalVariables*>(Super::GetRuntimeGVs(Asset));
	}
};
