// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyGlobalVariables.h"
#include "Fear_Of_A_Blak_PlanetGlobalVariables.generated.h"
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
#endif

/** Global Articy Variables */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	
	 UFear_Of_A_Blak_PlanetGlobalVariables() 
	{
		/** create the namespaces */
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static UFear_Of_A_Blak_PlanetGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<UFear_Of_A_Blak_PlanetGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#if !((defined(PLATFORM_PS4) && PLATFORM_PS4) || (defined(PLATFORM_PS5) && PLATFORM_PS5))
#pragma warning(pop)
#endif
