// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyTypeSystem.h"
#include "Fear_Of_A_Blak_PlanetTypeSystem.generated.h"

/** Articy Type System */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetTypeSystem : public UArticyTypeSystem
{
	GENERATED_BODY()
	
};
