// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "CoreUObject.h"
#include "ArticyRuntime/Public/ArticyBaseInclude.h"
#include "Fear_Of_A_Blak_PlanetInterfaces.h"
#include "Fear_Of_A_Blak_PlanetArticyTypes.generated.h"


/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef Sex */
class EFear_Of_A_Blak_PlanetSex : uint8
{
	Male = 0,
	Female = 1,
	Unknown = 2,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef ShapeType */
class EFear_Of_A_Blak_PlanetShapeType : uint8
{
	Invalid = 0,
	Spot = 1,
	Circle = 2,
	Rectangle = 3,
	Path = 4,
	Polygon = 5,
	Link = 6,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef SelectabilityModes */
class EFear_Of_A_Blak_PlanetSelectabilityModes : uint8
{
	Unselectable = 0,
	Selectable = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef VisibilityModes */
class EFear_Of_A_Blak_PlanetVisibilityModes : uint8
{
	Invisible = 0,
	Visible = 1,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef OutlineStyle */
class EFear_Of_A_Blak_PlanetOutlineStyle : uint8
{
	Solid = 0,
	Dot = 1,
	Dash = 2,
	DashDot = 3,
	DashDotDot = 4,
};

/** -------------------------------------------------------------------------------- */

UENUM(BlueprintType)
enum
/** UENUM generated form ArticyObjectDef PathCaps */
class EFear_Of_A_Blak_PlanetPathCaps : uint8
{
	ColoredDot = 0,
	None = 1,
	LineArrowHead = 2,
	FilledArrowHead = 3,
	Diamond = 4,
	Square = 5,
	Disc = 6,
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef FlowFragment */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetFlowFragment : public UArticyFlowFragment,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Dialogue */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDialogue : public UArticyDialogue,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef DialogueFragment */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDialogueFragment : public UArticyDialogueFragment,
 public IArticyObjectWithMenuText,
 public IArticyObjectWithStageDirections,
 public IArticyObjectWithSpeaker,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="MenuText"))
	FText MenuText = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StageDirections"))
	FText StageDirections = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Speaker"))
	FArticyId Speaker;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="SplitHeight"))
	float SplitHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Hub */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetHub : public UArticyHub,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Comment */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetComment : public UArticyComment,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedBy"))
	FText CreatedBy = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CreatedOn"))
	FDateTime CreatedOn;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Jump */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetJump : public UArticyJump,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Entity */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetEntity : public UArticyEntity,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Basic Character Properties Feature */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDefaultBasicCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Age"))
	float Age = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Species"))
	FText Species = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Born in"))
	FText BornIn = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Sex"))
	EFear_Of_A_Blak_PlanetSex Sex;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Profession"))
	FText Occupation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Voice"))
	FText Accent = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Personality"))
	FText Personality = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Appearance"))
	FText Appearance = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef DefaultSupportingCharacterTemplate */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDefaultSupportingCharacterTemplate : public UFear_Of_A_Blak_PlanetEntity,
 public IFear_Of_A_Blak_PlanetObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** IFear_Of_A_Blak_PlanetObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UFear_Of_A_Blak_PlanetDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UFear_Of_A_Blak_PlanetDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Extended Character Properties Feature */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDefaultExtendedCharacterFeatureFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Goals"))
	FText Motivation = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Inner Conflict"))
	FText InnerConflict = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Skills"))
	FText Skills = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Weaknesses"))
	FText Fears = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Quirks / Habits"))
	FText Habits = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Further Details"))
	FText FurtherDetails = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef DefaultMainCharacterTemplate */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDefaultMainCharacterTemplate : public UFear_Of_A_Blak_PlanetEntity,
 public IFear_Of_A_Blak_PlanetObjectWithDefaultExtendedCharacterFeatureFeature,
 public IFear_Of_A_Blak_PlanetObjectWithDefaultBasicCharacterFeatureFeature
{
	GENERATED_BODY()
	
public:
	
	/** IFear_Of_A_Blak_PlanetObjectWithDefaultExtendedCharacterFeatureFeature implementation */
	UFear_Of_A_Blak_PlanetDefaultExtendedCharacterFeatureFeature* GetFeatureDefaultExtendedCharacterFeature() const override
	{
		return DefaultExtendedCharacterFeature;
	}
	/** IFear_Of_A_Blak_PlanetObjectWithDefaultBasicCharacterFeatureFeature implementation */
	UFear_Of_A_Blak_PlanetDefaultBasicCharacterFeatureFeature* GetFeatureDefaultBasicCharacterFeature() const override
	{
		return DefaultBasicCharacterFeature;
	}
	/** Extended Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UFear_Of_A_Blak_PlanetDefaultExtendedCharacterFeatureFeature* DefaultExtendedCharacterFeature;
	/** Basic Character Properties */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UFear_Of_A_Blak_PlanetDefaultBasicCharacterFeatureFeature* DefaultBasicCharacterFeature;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from Articy Item Basics Feature */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetItemBasicsFeature : public UArticyBaseFeature
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Quest Item"))
	bool QuestItem = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Number"))
	float NumberValue = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Item Flavor Text"))
	FText FlavorText = FText::GetEmpty();
};
/** UCLASS generated from ArticyObjectDef Item */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetItem : public UFear_Of_A_Blak_PlanetEntity,
 public IFear_Of_A_Blak_PlanetObjectWithItemBasicsFeature
{
	GENERATED_BODY()
	
public:
	
	/** IFear_Of_A_Blak_PlanetObjectWithItemBasicsFeature implementation */
	UFear_Of_A_Blak_PlanetItemBasicsFeature* GetFeatureItemBasics() const override
	{
		return ItemBasics;
	}
	/** Item Basics */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	UFear_Of_A_Blak_PlanetItemBasicsFeature* ItemBasics;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Location */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetLocation : public UArticyLocation,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Spot */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetSpot : public UArticySpot,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EFear_Of_A_Blak_PlanetOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Zone */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetZone : public UArticyZone,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EFear_Of_A_Blak_PlanetShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EFear_Of_A_Blak_PlanetOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Path */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetPath : public UArticyPath,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EFear_Of_A_Blak_PlanetOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="StartCap"))
	EFear_Of_A_Blak_PlanetPathCaps StartCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="EndCap"))
	EFear_Of_A_Blak_PlanetPathCaps EndCap;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="LineWidth"))
	float LineWidth = 0.f;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Link */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetLink : public UArticyLink,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithTarget,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Target"))
	FArticyId Target;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Asset */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetAsset : public UArticyAsset,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Filename"))
	FText Filename = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OriginalSource"))
	FText OriginalSource = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Condition */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetCondition : public UArticyCondition,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptCondition* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Instruction */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetInstruction : public UArticyInstruction,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId,
 public IArticyObjectWithColor
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Expression"))
	UArticyScriptInstruction* Expression = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="InputPins"))
	TArray<UArticyInputPin*> InputPins;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutputPins"))
	TArray<UArticyOutputPin*> OutputPins;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationText */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetLocationText : public UArticyLocationText,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EFear_Of_A_Blak_PlanetShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EFear_Of_A_Blak_PlanetOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedWidth"))
	float ForcedWidth = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ForcedHeight"))
	float ForcedHeight = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef LocationImage */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetLocationImage : public UArticyLocationImage,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithVertices,
 public IArticyObjectWithTransform,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Anchors"))
	TArray<FArticyLocationAnchor> Anchors;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Vertices"))
	TArray<FVector2D> Vertices;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Transform"))
	UArticyTransformation* Transform = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShapeType"))
	EFear_Of_A_Blak_PlanetShapeType ShapeType;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Visibility"))
	EFear_Of_A_Blak_PlanetVisibilityModes Visibility;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineColor"))
	FLinearColor OutlineColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineSize"))
	float OutlineSize = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="OutlineStyle"))
	EFear_Of_A_Blak_PlanetOutlineStyle OutlineStyle;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Selectability"))
	EFear_Of_A_Blak_PlanetSelectabilityModes Selectability;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DropShadow"))
	bool DropShadow = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ClipRect"))
	FArticyRect ClipRect;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageOpacity"))
	float ImageOpacity = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ImageAsset"))
	FArticyId ImageAsset;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageWidth"))
	int32 CachedImageWidth = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="CachedImageHeight"))
	int32 CachedImageHeight = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShowDisplayName"))
	bool ShowDisplayName = false;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameColor"))
	FLinearColor DisplayNameColor = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayNameSize"))
	int32 DisplayNameSize = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef Document */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetDocument : public UArticyDocument,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef TextObject */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetTextObject : public UArticyTextObject,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithAttachments,
 public IArticyObjectWithPreviewImage,
 public IArticyObjectWithColor,
 public IArticyObjectWithText,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithPosition,
 public IArticyObjectWithZIndex,
 public IArticyObjectWithSize,
 public IArticyObjectWithShortId
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Attachments"))
	TArray<FArticyId> Attachments;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="PreviewImage"))
	UArticyPreviewImage* PreviewImage = nullptr;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Color"))
	FLinearColor Color = FLinearColor::Black;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Text"))
	FText Text = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Position"))
	FVector2D Position = FVector2D::ZeroVector;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="Size"))
	FArticySize Size;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
};

/** -------------------------------------------------------------------------------- */

/** UCLASS generated from ArticyObjectDef UserFolder */
UCLASS(BlueprintType)
class DEMOENVIRONMENT_API UFear_Of_A_Blak_PlanetUserFolder : public UArticyUserFolder,
 public IArticyObjectWithDisplayName,
 public IArticyObjectWithExternalId,
 public IArticyObjectWithShortId,
 public IArticyObjectWithZIndex
{
	GENERATED_BODY()
	
public:
	
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="DisplayName"))
	FText DisplayName = FText::GetEmpty();
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ExternalId"))
	FString ExternalId = TEXT("");
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ShortId"))
	int32 ShortId = 0;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(DisplayName="ZIndex"))
	float ZIndex = 0.f;
};
